#!/bin/bash
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BIN_DIR=$ROOT_DIR/bin
cd $BIN_DIR

VERSION="3.3.0"
CLASSPATH=.:$BIN_DIR/../sdk/Iddk2000-$VERSION.jar
export LD_LIBRARY_PATH=$BIN_DIR/../sdk:$LD_LIBRARY_PATH
java -DresultDir=$@ -cp $CLASSPATH com.iritech.demo.Iddk2000Main
